with first_temp as (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST 
    FROM ACTIVITY
    GROUP BY 1
)

SELECT round(COUNT( DISTINCT F.PLAYER_ID)/(SELECT count(DISTINCT player_id) FROM activity), 2) as fraction
FROM FIRST_TEMP F
JOIN ACTIVITY A
ON F.PLAYER_ID = A.PLAYER_ID
WHERE DATEDIFF(A.EVENT_DATE, F.first) = 1